apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: product-demo
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: acr-credentials
      containers:
        - name: product-service
          image: crpi-0jc2w0gzk6ynnrh2.cn-hongkong.personal.cr.aliyuncs.com/tekton-demo/product-service:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
